services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fyle-backend-intern-challenge-image:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: core/server.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-custom-image-test:latest
    command: pytest -vvv -s tests/
    environment:
      FLASK_APP: core/server.py
    volumes:
      - .:/app
